server:
  port: 8083

spring:
  application:
    name: fraud-decision-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/fraud_db
    username: ${DB_USER:fraud_user}
    password: ${DB_PASS:fraud_pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: FraudDecisionHikariPool
      maximum-pool-size: 8
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: fraud-decision-group
      auto-offset-reset: earliest

kafka:
  topics:
    risk-scored: risk.scored
    fraud-decision-made: fraud.decision.made

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
